### ISSUE TITLE
Context is undefined

### ISSUE THREAD

**Issue by thced** [cobraz/pubsub-http-handler#177]
Are there any on-going work in this area?

https://github.com/cobraz/pubsub-http-handler/blob/27fc1e08ca66993720996f9edd7bae9efd91340b/src/__tests__/fastify-plugin.test.ts#L31

**Comment by runeh** [comment]
I commented on https://github.com/cobraz/pubsub-http-handler/pull/178 now, regarding context.

Are there any requirements you have that should be taken into account?
