### ISSUE TITLE
Upgrade to Fastify v4

### ISSUE THREAD

**Issue by SimenB** [cobraz/pubsub-http-handler#71]
**Is your feature request related to a problem? Please describe.**

https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e is out

**Describe the solution you'd like**

N/A

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by cobraz** [comment]
Thanks!

**Comment by cobraz** [comment]
This is fixed in [v4](https://github.com/cobraz/pubsub-http-handler/releases/tag/v4.0.0). You can read the [migration guide](https://github.com/cobraz/pubsub-http-handler/blob/v4.0.0/migrate-from-v2-and-v3.md) for more information.
